version: "1"
rules:                              # Array of rules
  - base: master                    # Required. Target branch
    upstream: Mermade:master        # Required. Must be in the same fork network.
    mergeMethod: merge              # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
    mergeUnstable: false            # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: master
    upstream: master                # Required. Can be a branch in the same forked repo.
    assignees:                      # Optional
      - chriszo111
      - DeRRudi77
      - mvgijssel
      - saida
      - martijnrusschen
      - hardikr
    conflictReviewers:              # Optional, on merge conflict assign a reviewer
      - chriszo111
      - DeRRudi77
      - mvgijssel
      - saida
      - martijnrusschen
      - hardikr
label: ":arrow_heading_down: pull"  # Optional
